class EActionTypes:
    OPEN_WORKSPACE_SELECTOR = 1
    ADD_FOLDER = 2
    REMOVE_FOLDER = 3
    FOLDER_CHANGED = 4
    TOGGLE_PIN = 5
    BEGIN_SNAPSHOT = 6
    OPEN_NOTES = 7
    NEW_FLASHCARD = 8
    SHOW_WIDGET = 9
    HIDE_WIDGET = 10